### ISSUE TITLE
Platforms

### ISSUE THREAD

**Issue by ebf34e12952930cf** [toddw123/RotMG_Clientless#12]
Should there be support for different platforms (steam/kong)? It can be auto-detect for ease of use, since it has the platform in the GUID.

**Comment by toddw123** [comment]
what do you mean the platform is in the guid? And this is something i dont see as being that important at the moment, but if you want to add it i will review and merge it if it looks good. Otherwise this would probably be one of the last things i will get around to adding, as i think anyone playing with this can just migrate their account if they really want to use this in its current state on their main account. Me personally, im only using random mules/accounts ive made just for this since i dont want to get banned on my main if ive left out a particular packet somewhere.

**Comment by ebf34e12952930cf** [comment]
`what do you mean the platform is in the guid?`
For other platforms the guid look like `kongregate:number`, `steamworks:number`, etc. I have a few mules on other platforms, other than that I dont really have any use for it, but I guess someone may want to have a Treasure Map farming bot or something.

**Comment by toddw123** [comment]
Oh i didnt realize other platform guid's looked like that. My main account is a steam account but i migrated it to web so its just a regular email address now. 

It should be fairly easy to implement something for the different platforms though, not sure when i would get around to it but yeah i think eventually it would be good to have.
