### ISSUE TITLE
'sOut': unknown override specifier

### ISSUE THREAD

**Issue by ghost** [toddw123/RotMG_Clientless#51]
I'm getting this error plus many other errors, im not sure whats happening.

All errors, https://i.gyazo.com/2ba7ca00273297af0f506844db2dda30.png

**Comment by toddw123** [comment]
Did you change anything in the code? Did you download and set up the 2 required libraries like you are suppose to? You clearly missed something when trying to compile it, i just dont know what since it could be any number of things. But when you run into situations like this where there are an absurd number of errors, chances are you didnt set something up correctly (like one of the libraries that are required).
