### ISSUE TITLE
ShowEffect Updated

### ISSUE THREAD

**Issue by Zeroeh** [toddw123/RotMG_Clientless#53]
A new variable in the ShowEffect packet was added: Duration
CBA to do a pull request... btw, it's a float

 [Old Packet](https://image.prntscr.com/image/P95PAzCQTqahAjRhs5JuYQ.png)

 [New Packet](https://image.prntscr.com/image/Rrp0DtOUTs_ZwZQFTB3g4Q.png)

**Comment by toddw123** [comment]
Good catch, thanks for pointing this out! 

Ill get the packet structure updated right now.


edit: im also not sure why deca feels like using a `float` when the AS3 `number` variable is actually a `double` in C/C++. A `double` is much more reliable. Although my guess is its due to a `double` being 6 bytes whereas a `float` is just 4. So they end up saving a negligible amount of space.
